# Generated by Django 3.0.5 on 2020-08-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
